= RHDG Workshop - Infra
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2023-07
// Metadata
:description: This repository contains the automation to deploy the RHDG workshop
:keywords: infinispan, datagrid, openshift, red hat, automation
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 3
:sectnums: 
:source-highlighter: pygments
:imagesdir: docs/images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// Icons for GitHub
:yes: :heavy_check_mark:
:no: :x:
endif::[]
ifndef::env-github[]
:icons: font
// Icons not for GitHub
:yes: icon:check[]
:no: icon:times[]
endif::[]

// Create the Table of contents here
toc::[]


== Introduction 

This repository contains the automation to deploy the RHDG workshop.


== How to install

Deploying the cluster is pretty simple:

* First, execute the `./auto-install.sh` of this git repository. This will create namespaces for users with correct permissions, users to access the namespaces, and the Subscription to install the RHDG operator.
* Second, use the `./auto-install.sh` of the https://github.com/alvarolop/quarkus-observability-app[quarkus-observability-app] to install the observability components.



== Side services


This automation deploys two side services that help participants explore common configuration needs like accessing a Database for in-line caching and persistence; and also an LDAP server, to validate the credentials of users against an external source of users. Therefore, the Helm Chart present in this repository deploys:

* An OpenLDAP server in the `ldap` namespace.
* A PostgreSQL database in the `user1-db` namespace.


=== PostgreSQL


* In is based on the RHEL 9 - PostgreSQL database image certified and provided by Red Hat: https://catalog.redhat.com/software/containers/rhel9/postgresql-15/63f763f779eb1214c4d6fcf6?container-tabs=overview
* The deployment method is an adjustment of the official templates distributed by Red Hat on Openshift clusters. The original templates related to PostgreSQL were exported to the folder `openshift-templates` for further documentation.
* The full documentation of the container image is located in the RH Software Collections organization at Github: https://github.com/sclorg/postgresql-container/tree/master


*How to check that PostgreSQL works fine?*


.Deploy the solution in the cluster
[source, bash]
----
oc apply -f solutions/solution-datasource.yaml
----


=== OpenLDAP













== Deprecated: How to create second oauth source

.Create the htpasswd file
[source, bash]
---
touch temporal-workshop-users.htpasswd
for userId in {1..100}; do htpasswd -b -B temporal-workshop-users.htpasswd user$userId openshift; done
---

.Create secret with the users and pass
[source, yaml]
---
apiVersion: v1
kind: Secret
metadata:
  name: workshop-htpasswd-secret
  namespace: openshift-config
type: Opaque 
stringData:
  htpasswd: |
    {{- range $user := untilStep 1 (int .Values.ocp_users) 1 }}
    {{- $username := printf "%s%s" "user"  ( $user | toString) }}
    {{ htpasswd $username "openshift" }}
    {{- end }}
---
