---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  annotations:
    infinispan.org/podTargetLabels: 'domain,user'
    infinispan.org/targetLabels: domain
  name: cluster
  labels:
    domain: bookshop
    user: user1
spec:
  container:
    cpu: "2000m:100m"
    extraJvmOpts: '-Duser.timezone="Europe/Madrid"'
    memory: "1Gi:1Gi"
  expose:
    annotations: {}
    type: Route
  replicas: 1
  security:
    endpointAuthentication: true
    endpointSecretName: cluster-credentials
    authorization:
      enabled: true
    endpointEncryption:
      type: Service
  service:
    container:
      ephemeralStorage: true 
    type: DataGrid 
    sites:
      local:
        expose:
          type: ClusterIP
        maxRelayNodes: 1
        name: SiteB
      locations:
        - name: SiteA
          clusterName: cluster 
          namespace: user1-rhdg
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
type: Opaque
stringData:
  identities.yaml: |-
    credentials:
    - username: developer
      password: developer
    - username: admin
      password: password
      roles:
        - admin
    - username: user1
      password: openshift
      roles:
        - application
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: cluster-rest-proto
spec:
  clusterName: cluster
  name:  rest-proto
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: 2
      statistics: "true"
      encoding:
        key:
          mediaType: application/x-protostream
        value:
          mediaType: application/x-protostream
      backups: 
        SiteA: 
          backup: 
            strategy: "SYNC"
            twoPhaseCommit: "false"
  updates:
    strategy: recreate
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: cluster-rest-plain
spec:
  clusterName: cluster
  name:  rest-plain
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: 2
      statistics: "true"
      encoding:
        key:
          mediaType: text/plain
        value:
          mediaType: text/plain
  updates:
    strategy: recreate
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: cluster-rest-json
spec:
  clusterName: cluster
  name:  rest-json
  template: |-
    distributedCache:
      mode: "SYNC"
      owners: 2
      statistics: "true"
      encoding:
        key:
          mediaType: application/json
        value:
          mediaType: application/json
  updates:
    strategy: recreate
