{{- $count := .Values.users | add1 }}
{{- range $user := untilStep 1 (int $count) 1 }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: user{{ $user }}
users:
  - user{{ $user }}
{{- end }}
---
#Allow users to view resources in the operator namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user{{ $user }}-view
  namespace: rhdg-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: user{{ $user }}
    apiGroup: rbac.authorization.k8s.io