{{- $count := .Values.users | add1 }}
{{- range $user := untilStep 1 (int $count) 1 }}
---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: user{{ $user }}
users:
  - user{{ $user }}
{{- end }}
