---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: {{ $.Values.rhdg.operator.namespace }}
  annotations:
    openshift.io/description: "This project contains all the resources related to the operator of Red Hat Data Grid 8"
    openshift.io/display-name: "RH Data Grid 8 - Operator"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: datagrid
  namespace: {{ $.Values.rhdg.operator.namespace }}
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: datagrid-operator
  namespace: {{ $.Values.rhdg.operator.namespace }}
spec:
  channel: 8.4.x
  installPlanApproval: Automatic 
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
