# Default values for cluster-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Due to a bug, the following variable creates one user less.
users: 4

ocp_users: 20

namespaces: 
  - rhdg-operator
  - rhdg1
  - rhdg2

gitops:
  namespace: gitops
  cluster: argocd