# Default values for cluster-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

users: 15

ocp_users: 20

namespaces: 
  # - rhdg-operator
  - rhdg
  - rhdg-2

gitops:
  namespace: gitops
  cluster: argocd

openldap:
  namespace: openldap
  name: server
  sa_name: openldap

rhdg:
  operator:
    namespace: rhdg-operator